djangoProject3/urls.py
from django.contrib import admin
from django.urls import path, include

from survey import views

urlpatterns = [
    path('', include('survey.urls')),
    path('admin/', admin.site.urls),
   # path('api/', include('survey.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

survey/urls.py
from django.urls import path

from . import views
from .views import SurveyViewApi


urlpatterns = [
    path('', views.SurveyListView.as_view()),
    path('add_answer/<int:pk>', views.SurveyDetailView.as_view(), name='add_answer'),
    path('api/surveys/', SurveyViewApi.as_view()),
]

survey/models.py
from django.contrib.auth import get_user_model
from django.db import models
User = get_user_model()


questions = (
    ('text_field', 'Ответ текстом'),
    ('radio', 'Один вариант'),
    ('check_boxes', 'Выбор нескольких вариантов')
)


class Question(models.Model):
    text = models.TextField()
    type = models.CharField(
        choices=questions,
        verbose_name='Тип вопроса',
        max_length=20
    )

    def __str__(self):
        return self.text


class Choice(models.Model):
    text = models.TextField(verbose_name='Вариант ответа')
    questions = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')

    def __str__(self):
        return self.text


class Survey(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name')
    start_date = models.DateField(auto_now_add=True, verbose_name='Start date')
    end_date = models.DateField(verbose_name='End date')
    description = models.CharField(max_length=200, verbose_name='Description')
    question = models.ForeignKey(
        Question, blank=True, on_delete=models.CASCADE,
        related_name="surveys",
    )
    url = models.SlugField(max_length=160, unique=True, null=True)

    def __str__(self):
        return self.name


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users', default=0)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, related_name='survey', default='')
    many_choice = models.ManyToManyField(Choice, related_name='many_answer')
    one_choice = models.ForeignKey(Choice, null=True, on_delete=models.CASCADE, related_name='one_answer')
    text = models.TextField(null=True)

    def __str__(self):
        return self.text

survey/forms.py
from .models import Answer

from django import forms


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('text', )

survey/views.py
#from django.http import request
from django.http.request import HttpRequest
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Survey
from .serializers import SurveySerializer
from django.views.generic import ListView
from .forms import AnswerForm


class SurveyViewApi(APIView):
    model = Survey
    queryset = Survey.objects.all()

    def get(self, request):
        surveys = Survey.objects.all()
        serializer = SurveySerializer(surveys, many=True)
        return Response({"surveys": serializer.data})

    def post(self, request):
        survey_saved = 0
        survey = request.data.get('survey')
        serializer = SurveySerializer(data=survey)
        if serializer.is_valid(raise_exception=True):
            survey_saved = serializer.save()
        return Response({"success": "Survey '{}' created successfully".format(survey_saved.name)})


class SurveyView(View):
    model = Survey
    queryset = Survey.objects.all()
    template_name = 'surveys/surveys_list.html'


class SurveyListView(ListView):
    model = Survey
    queryset = Survey.objects.all()
    template_name = 'surveys/surveys_list.html'

    def add_answer(self, request, pk):
        #submit_button = request.POST.get("submit")

        form = AnswerForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data.get("text")
            print(text)
            form = form.save(commit=False)
            form.survey_id = pk
            form.save()
        print(request.POST)
        return HttpResponseRedirect('/')


class SurveyDetailView(DetailView):
    model = Survey
    slug_field = 'url'
    template_name = 'surveys/survey_detail.html'

templates/surveys/base.html
{% block content %}
<section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
            {% block container %}
            <div class="container-fluid py-md-3">
            {% endblock container %}
                <div class="row">
                {% block sidebar %}
                <div class="side-bar col-lg-3">
                {% endblock sidebar %}
                </div>
                    {%  block survey  %}
                    {% endblock survey %}
                </div>
            </div>
</section>
{% endblock content %}

{% if survey.question.type == 'text_field' %}
                                    <input type="text" size="40">
                                    <a href="{% url 'create' %}"><button type="submit">Добавить ответ</button></a>
                                    <button type="submit">Добавить ответ</button>
                                {% endif %}

templates/surveys/survey_detail.html
   <div class="left-ads-display col-lg-9">
        <div class="row">
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                   Опрос: {{ survey.name }}
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">Вопрос: {{ survey.question }}</span>
                                </div>
                            </div>
                            <div class="answer">


                            <form action="{% url 'add_answer' survey.id %}" method="POST" id="formAnswer">
                            {% csrf_token %}

                                <label>
                                    Ваш комент
                                </label>

                                <input type="text" size="40" name="text" class="glyphicon-object-align-left">
                                <button type="Submit" name="submit" value="Submit">Ваш комент</button>

                            </form>
                            </div>
                            <ul class="stars">
                                <li>
                                </li>
                                <li>
                                </li>
                                <li>
                                </li>
                                <li>
                                </li>
                                <li>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
        </div>
    </div>

templates/surveys/surveys_list.html
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for survey in survey_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                   Опрос: {{ survey.name }}
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">Вопрос: {{ survey.question }}</span>
                                </div>
                            </div>
                            <div class="answer">

                            <form action="{% url 'add_answer' survey.id %}" method="post" id="formAnswer">
                            {% csrf_token %}

                                    <label>
                                        Ваш комент
                                        </label>

                                    <input type="text" size="40" name="text">
                                    <button type="Submit" name="submit" value="Submit">Ваш комент</button>

                                {% if submitbutton == "Submit" %}
                                    <h1>Your first name is {{ text }}</h1>

                                {% endif %}

                            </form>
                            </div>
                            <ul class="stars">
                                <li>
                                </li>
                                <li>
                                </li>
                                <li>
                                </li>
                                <li>
                                </li>
                                <li>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>